### ISSUE TITLE
Some important package needs to be installed before deploying contrail-operator

### ISSUE THREAD

**Issue by pnkjkragrl** [Juniper/contrail-operator#455]
While deploying contrail-operator, found the some mandatory package needs to be installed in order for deployment to work fine.

before installing bazel run //cmd/crdsloader:contrail-operator-crdsloader-push-local
We have to install python3 and patch tool

yum install python3
yum install patch

Please add this in README file

**Comment by kabart** [comment]
Resolved:
https://github.com/Juniper/contrail-operator/pull/506
