### ISSUE TITLE
Deployment of pods failed due to error mentioned in desc

### ISSUE THREAD

**Issue by pnkjkragrl** [Juniper/contrail-operator#503]
[root@pankaj-contrail-operator-node1 env]# ./apply_contrail_cluster.sh 
namespace/contrail unchanged
role.rbac.authorization.k8s.io/contrail-operator configured
clusterrole.rbac.authorization.k8s.io/contrail-operator unchanged
serviceaccount/contrail-operator unchanged
rolebinding.rbac.authorization.k8s.io/contrail-operator unchanged
clusterrolebinding.rbac.authorization.k8s.io/contrail-operator unchanged
deployment.apps/contrail-operator unchanged
pod/contrail-operator-544f9c7c44-jgzt8 condition met
secret/cluster1-admin-password configured
**error: error validating "deploy/cluster.yaml": error validating data: [ValidationError(Manager.spec): unknown field "keystoneSecretInstance" in net.juniper.contrail.v1alpha1.Manager.spec, ValidationError(Manager.spec.services.command.spec.serviceConfiguration): unknown field "swiftProxyPort" in net.juniper.contrail.v1alpha1.Manager.spec.services.command.spec.serviceConfiguration, ValidationError(Manager.spec.services.controls[0].spec.serviceConfiguration): unknown field "zookeeperInstance" in net.juniper.contrail.v1alpha1.Manager.spec.services.controls.spec.serviceConfiguration]; if you choose to ignore these errors, turn validation off with --validate=false**

**Workaround :- ** Remove the unknown fields mentioned in error from cluster.yaml and then it will work 

Please correct this in code

**Comment by kabart** [comment]
Resolved:
https://github.com/Juniper/contrail-operator/pull/506
