### ISSUE TITLE
'Failed to create thread: Resource temporarily unavailable (11)' in rabbitmq sts when CPU cores > 64

### ISSUE THREAD

**Issue by e-minguez** [Juniper/contrail-operator#534]
rabbitmq0 pod was crashloop back with the subject log.

According to some [docs](https://www.ibm.com/support/knowledgecenter/SSQNUZ_3.0.1/cpd/troubleshoot/ts_rabbitmq_ha_issue.html) it seems in environments that have nodes with 64 or more CPU cores,  rabbitmq may fail to start. I've fixed it by:

```
oc set env sts -n contrail rabbitmq1-rabbitmq-statefulset RABBITMQ_IO_THREAD_POOL_SIZE=128

oc delete pod -n contrail rabbitmq1-rabbitmq-statefulset-0 rabbitmq1-rabbitmq-statefulset-1 rab
tmq1-rabbitmq-statefulset-2
```

**Comment by Dysproz** [comment]
Hi @e-minguez,
contrail-operator has migrated to Tungsten Fabric now.

https://github.com/tungstenfabric/tf-operator

**Comment by Dysproz** [comment]
And if you want to fill a bug here's the Tungsten Fabric Jira :)

https://jira.tungsten.io/projects/TFB/issues/TFB-15?filter=allopenissues
